<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.5.1" />
    <PackageReference Include="PdfPig" Version="0.1.16" />
    <ProjectReference Include="..\..\src\Odyssey.Core\Odyssey.Core.csproj" />
    <ProjectReference Include="..\..\src\Odyssey.Infrastructure\Odyssey.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Odyssey.Search\Odyssey.Search.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
